### ISSUE TITLE
[PRO][] OFFERER (page /structures)

### ISSUE THREAD

**Issue by annemarie35** [betagouv/pass-culture-browser#345]
Quand je créé un compte et que j'arrive sur la page structures 

- [x] je vois un bandeau vert, 'le rattachement de la structure, bla bla bla...'
- [x] je vois juste le message 'En cours de validation....'
- [x] je peux ajouter un lieu même si ma structure n'est pas validée

Quand je créé une nouvelle structure

- [x]  Si j'ajoute une structure mais qu'elle n'a pas encore de lieu, On affiche "Créez un lieu pour pouvoir y associer des offres." Pas de btn "nouvelle offre", pas de décompte des offres, pas de décompte des lieux : il faut aller dans la page de détail de la structure pour ajouter le lieux.
- [x] BUG ? si je rajoute une structure, le bandeau vert qui m'indique que 'Votre structure a bien été enregistrée, elle est en cours de validation.' s'affiche alors que la structure est active par défaut   #350

Si ma structure principale n'est pas encore validée

- [x] Gérer l'affichage différement si la structure est validée ou pas, pour le moment l'affichage est conditionné par isActive et le isValidated n'est pas encore implémenté côté api @arnoo  #349

Si je n'ai pas ajouté de lieu

- [ ] si je clique sur offre mais que je n'ai pas de lieu > que se passe-t-il ? #353 

**Remarques** 

- ça n'affiche pas toujours correctement le nombre d'offres mais comme ça touche aux selectors, j'ai laissé de côté.
- Une offre sans date n'apparaît pas non plus

Branche https://github.com/betagouv/pass-culture-pro/commits/fix-offerer-item-informations-display

![capture d ecran 2018-06-25 a 17 44 12](https://user-images.githubusercontent.com/7688741/41860528-2f8bd8e2-789f-11e8-84f4-880ac72cb873.png)

**Comment by annemarie35** [comment]
<img width="966" alt="capture d ecran 2018-06-22 a 17 47 10" src="https://user-images.githubusercontent.com/7688741/41785862-2e89a616-7644-11e8-8c25-bf665adf9fc9.png">

**Comment by annemarie35** [comment]
Si j'ajoute une structure mais qu'elle n'a pas encore de lieu : 

<img width="433" alt="capture d ecran 2018-06-22 a 15 43 13" src="https://user-images.githubusercontent.com/7688741/41786004-98d572e8-7644-11e8-8be4-5b935eb7b585.png">

**Comment by annemarie35** [comment]
Je suis une nouvelle structure, je vois quand même VOS OFFRES sur le menu mais si je clique j'ai un messages qui m'explique ce qu'il manque 
`Vous devez avoir déjà enregistré un lieu dans une de vos structures pour ajouter des offres`

**Comment by annemarie35** [comment]
<img width="796" alt="capture d ecran 2018-06-25 a 14 43 40" src="https://user-images.githubusercontent.com/7688741/41850820-4482bcfc-7886-11e8-863d-a33c9ac52251.png">

3 cas de figures déjà

**Comment by annemarie35** [comment]
![capture d ecran 2018-06-25 a 17 35 02](https://user-images.githubusercontent.com/7688741/41860124-181c6e7a-789e-11e8-9544-88b8ad1eca01.png)

**Comment by annemarie35** [comment]
![capture d ecran 2018-06-25 a 17 44 12](https://user-images.githubusercontent.com/7688741/41860528-2f8bd8e2-789f-11e8-84f4-880ac72cb873.png)

**Comment by annemarie35** [comment]
ça n'affiche pas toujours correctement le nombre d'offres mais comme ça touche aux selectors, j'ai laissé de côté.
Une offre sans date n'apparait pas non plus

**Comment by annemarie35** [comment]
Je garde cette issue comme base de tests pour les tests e2e
